//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSalonBelleza.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual users users { get; set; }
    }
}
