//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSalonBelleza.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas
    {
        public int id_cita { get; set; }
        public string estilista { get; set; }
        public System.DateTime fecha { get; set; }
        public string sede { get; set; }
        public string nombre_cliente { get; set; }
        public string servicio { get; set; }
        public string descripcion_servicio { get; set; }
    }
}
