//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSalonBelleza
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public int id { get; set; }
        public long user_id { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual users users { get; set; }
    }
}
